version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/iam_system
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - mongodb
    healthcheck:
      test: [ 'CMD', 'node', './healthcheck.js' ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  mongodb:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  mongodb_data:
